version: '3'
services:
  keydb:
    image: eqalpha/keydb:x86_64_v6.3.4
    restart: unless-stopped
    volumes:
      - keydb_data:/data
    healthcheck:
      test: ["CMD-SHELL", "keydb-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: keydb-server /etc/keydb/keydb.conf --appendonly yes

  api:
    image: cry0this/meme-api:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDISCLOUD_URL=${REDISCLOUD_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/_health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      keydb:
        condition: service_healthy

volumes:
  postgres_data: {}
  keydb_data: {}
