version: '3'
services:
  keydb:
    image: eqalpha/keydb:x86_64_v6.3.4
    restart: unless-stopped
    volumes:
      - keydb_data:/data
    healthcheck:
      test: ["CMD-SHELL", "keydb-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: keydb-server /etc/keydb/keydb.conf --appendonly yes

  bot:
    image: cry0this/random-linux-memes-bot:latest
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDIS_URL=redis://keydb:6379/0
      - GO_REDDIT_CLIENT_ID=${GO_REDDIT_CLIENT_ID}
      - GO_REDDIT_CLIENT_SECRET=${GO_REDDIT_CLIENT_SECRET}
      - GO_REDDIT_CLIENT_USERNAME=${GO_REDDIT_CLIENT_USERNAME}
      - GO_REDDIT_CLIENT_PASSWORD=${GO_REDDIT_CLIENT_PASSWORD}
    depends_on:
      keydb:
        condition: service_healthy

volumes:
  keydb_data: {}
